# This is a basic workflow to help you get started with Actions
name: HTML5 Validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'esercizi/*.*'
  pull_request:
    branches: [ main ]
    paths:
      - 'esercizi/*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v5

    - name: HTML5 Validator
      # You may pin to the exact commit or the version.
      # uses: Cyb3r-Jak3/html5validator-action@02b835cb536d5a22714059a755940fa6f1f3fe1b
      uses: Cyb3r-Jak3/html5validator-action@v8.0.0
      with:
        # Path of the files to test
        root: esercizi/ # optional
        # Path of config file
        #config: # optional
        # Extra arguments to test with
        #extra: # optional
        # Format for logging output. Valid values: gnu,xml,json,text
        #format: # optional
        # Logging Level. Valid values: DEBUG, INFO, WARNING. Default: WARNING
        #log_level: DEBUG # optional, default is WARNING
        # Checks css as well
        #css: # optional
        # Files or directories to ignore in checking
        #blacklist: # optional
      continue-on-error: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: log
        path: log.log
